# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='app',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.Application'),
            preserve_default=False,
        ),
    ]
